# Generated by Django 6.0 on 2026-01-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketprompt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prompts', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='prompts.marketprompt'),
        ),
        migrations.AddField(
            model_name='comment',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prompts.marketprompt'),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.marketprompt', verbose_name='所属提示词'),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('user', 'prompt')},
        ),
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together={('prompt', 'version')},
        ),
    ]
